### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/woocommerce-checkout-field-editor-pro#1]
```
[09-Nov-2023 12:48:50 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /public_html/wp-content/plugins/woocommerce-checkout-field-editor-pro/includes/class-thwcfe-order-data.php:323
Stack trace:
#0 /public_html/wp-content/plugins/woocommerce-checkout-field-editor-pro/includes/class-thwcfe-order-data.php(323): array_merge()
#1 /public_html/wp-content/plugins/woocommerce-checkout-field-editor-pro/includes/class-thwcfe-order-data.php(292): THWCFE_Order_Data->prepare_order_meta_fields_for_email()
#2 /public_html/wp-includes/class-wp-hook.php(324): THWCFE_Order_Data->woo_email_order_meta_fields()
#3 /public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(488): apply_filters()
#5 /public_html/wp-includes/class-wp-hook.php(326): WC_Emails->order_meta()
#6 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /public_html/wp-content/plugins/woocommerce/templates/emails/customer-processing-order.php(45): do_action()
#9 /public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')
#10 /public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template()
#11 /public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php(113): wc_get_template_html()
#12 /public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(588): WC_Email_Customer_Processing_Order->get_content_html()
#13 /public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php(93): WC_Email->get_content()
#14 /public_html/wp-includes/class-wp-hook.php(324): WC_Email_Customer_Processing_Order->trigger()
#15 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 /public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#17 /public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array()
#18 /public_html/wp-includes/class-wp-hook.php(324): WC_Emails::send_transactional_email()
#19 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#20 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#21 /public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(404): do_action()
#22 /public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(253): WC_Order->status_transition()
#23 /public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(365): WC_Order->save()
#24 /public_html/wp-content/plugins/woocommerce/includes/gateways/cod/class-wc-gateway-cod.php(348): WC_Order->update_status()
#25 /public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1050): WC_Gateway_COD->process_payment()
#26 /public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1279): WC_Checkout->process_order_payment()
#27 /public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(508): WC_Checkout->process_checkout()
#28 /public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout()
#29 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#30 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#31 /public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#32 /public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax()
#33 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#34 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#35 /public_html/wp-includes/template-loader.php(13): do_action()
#36 /public_html/wp-blog-header.php(19): require_once('...')
#37 /public_html/index.php(17): require('...')
#38 {main}
  thrown in /public_html/wp-content/plugins/woocommerce-checkout-field-editor-pro/includes/class-thwcfe-order-data.php on line 323
```

https://github.com/pronamic/woocommerce-checkout-field-editor-pro/blob/92f51b361fe67ee8d93f965d2a052a55ff0659f5/includes/class-thwcfe-order-data.php#L297-L324

The function above is used in the `woocommerce_email_customer_details_fields` and `woocommerce_email_order_meta_fields` filters from WooCommerce:

https://github.com/pronamic/woocommerce-checkout-field-editor-pro/blob/92f51b361fe67ee8d93f965d2a052a55ff0659f5/includes/class-thwcfe-order-data.php#L50

https://github.com/pronamic/woocommerce-checkout-field-editor-pro/blob/92f51b361fe67ee8d93f965d2a052a55ff0659f5/includes/class-thwcfe-order-data.php#L47

- `woocommerce_email_customer_details_fields`
   https://github.com/woocommerce/woocommerce/blob/670e2c06693e5766e2be5157f9b2644b10367658/plugins/woocommerce/includes/class-wc-emails.php#L554
- `woocommerce_email_order_meta_fields`
   https://github.com/woocommerce/woocommerce/blob/670e2c06693e5766e2be5157f9b2644b10367658/plugins/woocommerce/includes/class-wc-emails.php#L488

**Comment by remcotolsma** [comment]
This problem is caused by another plugin:

- https://github.com/pronamic/woo-order-weight/issues/1
